import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';

const inter = Roboto_Slab({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-mainBlue`}>
        <nav>
          <div className="w-full text-right py-2 px-4 border-b-2 border-b-white border-dotted">
            Menu
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
