import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import NavigationTop from './components/NavigationTop';

const inter = Roboto_Slab({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NavigationTop />
      <body className={`${inter.className} bg-mainBlue`}>{children}</body>
    </html>
  );
}
